### PR TITLE
Update getting_started_with_lava.rst

### LINKED ISSUE #9: Paths to tutorials on the 'Getting Started' page are incorrect after directory restructure of core lava repo

### PR DESCRIPTION
**Pull request by drager-intel**
Updated paths to tutorials after directory restructure of core lava repo
Fixes #9

### CODE REVIEW

**Review by awintel — CHANGES_REQUESTED** [review]
MNIST link still broken

**Comment by drager-intel** [comment]
Fixed MNIST path. Build is still broken. @mgkwill ?

**Review by awintel — APPROVED** [review]
Looks good

**Comment by mgkwill** [comment]
> Fixed MNIST path. Build is still broken. @mgkwill ?

@drager-intel Thanks. Yeah I think the issue is that @bamsumit has this configured to do autodoc for lava-dl but CI doesn't currently pull the source for lava-dl or for that matter lava, so when the build runs it fails to find source to run autodocs.

**Review by mgkwill — APPROVED** [review]

**Pull request merged**
