### PR TITLE
Release/v0.5.1

### PR DESCRIPTION
**Pull request by weidel-p**
This PR updates the website to document Lava version 0.5.1 and the corresponding libraries.

Still left to do:
- [x] Fix formatting issues in lava-optimization. (lava-optimization/src/lava/lib/optimization/solvers/bayesian/solver.py and lava-optimization/src/lava/lib/optimization/solvers/bayesian/solver.py have faulty docstrings)
- [x] Check if the 'getting started' section is up to date with the current state of the libraries

### CODE REVIEW

**Comment by bamsumit** [comment]
I have noticed two things for now:
* image
I would suggest red portion to be collapsed as I would expect to get a summary/table of content of the modules here and this gets distracting
* image
Latex rendering is broken.

**Comment by weidel-p** [comment]
I changed the max-depth level to two to comply with @bamsumit request. I also think it's nicer like that. I also added the changes in the current lava-optimization PRs.

The equations will be rendered correctly in CI, just not on the machine I used for preview.

**Comment by bamsumit** [comment]
> I changed the max-depth level to two to comply with @bamsumit request. I also think it's nicer like that. I also added the changes in the current lava-optimization PRs.
> 
> The equations will be rendered correctly in CI, just not on the machine I used for preview.

I think there is one more level that needs change in max-depth level: 
image
Looks like that's only for lava-dl

**Comment by weidel-p** [comment]
Oh, sorry, I somehow thought that lava-dl was already formatted correctly. I now reduced the max-depth there, too.

**Review by bamsumit — APPROVED** [review]
Looks good not Philipp. Thanks :)

**Review by PhilippPlank — APPROVED** [review]

**Pull request merged**
